bengaltraining/urls.py
from .tokenSerializer import MyTokenObtainPairView
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    url(r'^frontend/',include('frontend.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^poll/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',include('polls.urls')),
    url(r'^api/poll/',include('polls.api.urls',namespace='api')),
    url(r'^api/user/',include('accounts.api.urls',namespace='api-user')),
    url(r'^api/token/$', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^api/token/verify/$', TokenVerifyView.as_view(), name='token_verify'),
]
urlpatterns += staticfiles_urlpatterns()

polls/api/urls.py
from django.conf.urls import url
from .views import (
    QuestionlistAPIView,
    QuestionDetailAPIView,
    QuestionUpdateAPIView,
    QuestionDeleteAPIView,
    QuestionCreateAPIView,
    InterestListAPIView,
)


urlpatterns = [
    url(r'^$',QuestionlistAPIView.as_view(),name='list'),
    url(r'^create/$',QuestionCreateAPIView.as_view(),name='create'),
    url(r'^interest/$',InterestListAPIView.as_view(),name='interest'),
    url(r'^(?P<id>[\w-]+)/$',QuestionDetailAPIView.as_view(),name='detail'),
    url(r'^(?P<id>[\w-]+)/update/$',QuestionUpdateAPIView.as_view(),name='update'),
    url(r'^(?P<id>[\w-]+)/delete/$',QuestionDeleteAPIView.as_view(),name='delete'),
    
    # url(r'^profile$',views.profile,name='profile'),
    # url(r'^admin$',views.admin,name='admin'),
    # url(r'^createpolls$',views.createpolls,name='createpoll'),
    # # ex: /polls/5/
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # url(r'^(?P<question_id>[0-9]+)/getdata/$', views.getdata, name='getdata'),
]   

polls/urls.py
from django.conf.urls import url
from . import views
app_name='polls'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^profile$',views.profile,name='profile'),
    url(r'^test$',views.test,name='test'),
    url(r'^admin$',views.admin,name='admin'),
    url(r'^createpolls$',views.createpolls,name='createpoll'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/getdata/$', views.getdata, name='getdata'),
    
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User
from profileinfo.models import interest

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,default=None)
    tag=models.ForeignKey(interest,default=None,blank=False)
    total = models.IntegerField(default=0)
    music = models.IntegerField(default=0)
    painting = models.IntegerField(default=0)
    poetry = models.IntegerField(default=0)
    technology = models.IntegerField(default=0)
    vote = models.IntegerField(default=0)
    
    def __str__(self):
        return self.question_text
        

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class VoteViewCounter(models.Model):
    Question=models.OneToOneField(Question, on_delete=models.CASCADE)
    votedUser=models.ManyToManyField(User,related_name = 'votedUser')
    viewedUser=models.ManyToManyField(User, related_name = 'viewedUser')
    
    
    

polls/forms.py
from django import forms
from . import models

class createpoll(forms.ModelForm):
    class Meta:
        model=models.Question
        fields=['question_text','tag']
  
    def clean_question_text(self):
        data = self.cleaned_data['question_text']  
        if "?" not in data:
            raise forms.ValidationError("Not a question")
        return data


class takechoice(forms.ModelForm):
    class Meta:
        model=models.Choice
        fields=['choice_text']
    def getit(self):
        return models.Choice.choice_text

polls/api/views.py
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    CreateAPIView,
    RetrieveDestroyAPIView,
    RetrieveUpdateAPIView

)
from rest_framework.response import Response
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,

)
from .pagination import questionpagenumberpagination
from rest_framework.filters import(
    SearchFilter,
    OrderingFilter
)

from .permissions import isowner
from .serializers import (
    PollDetailSerializers,
    PollListSerializers,
    PollCreateSerializers,
    InterestListSerializers,)

from .decorators import timer
from polls.models import Question,Choice,VoteViewCounter

from profileinfo.models import interest

class QuestionCreateAPIView(CreateAPIView):
    
    queryset=Question.objects.all()
    serializer_class=PollCreateSerializers
    permission_classes=[IsAuthenticated]

    @timer
    def post(self, request):
        tag=interest.objects.get(id=request.data['tag'])
        serializer = PollCreateSerializers(data=request.data)
        if serializer.is_valid(raise_exception=True):
            q = serializer.save(user=request.user)
            options=request.POST.getlist('options[]')
            for option in options:
                opt_obj=Choice(question=q,choice_text=option)
                opt_obj.save()
            counter=VoteViewCounter(Question=q)
            counter.save()
            counter.votedUser.add(request.user)
            counter.save()
            counter.viewedUser.add(request.user)
            counter.save()
        return Response(serializer.data)
            

    


class QuestionlistAPIView(ListAPIView):
    serializer_class=PollListSerializers
    filter_backends=[SearchFilter]
    search_fields = ['user__username','tag__title']
    pagination_class = questionpagenumberpagination

    def get_queryset(self,*args,**kwargs):
        query=Question.objects.order_by('-pub_date')
        return query

    

class QuestionDetailAPIView(RetrieveAPIView):
    queryset=Question.objects.all()
    serializer_class=PollDetailSerializers
    lookup_field='id'


class QuestionUpdateAPIView(RetrieveUpdateAPIView):
    queryset=Question.objects.all()
    serializer_class=PollDetailSerializers
    lookup_field='id'
    permission_classes=[IsAuthenticatedOrReadOnly,isowner]

class QuestionDeleteAPIView(RetrieveDestroyAPIView):
    queryset=Question.objects.all()
    serializer_class=PollDetailSerializers
    lookup_field='id'
    
    def get(self,request,id):
        question=Question.objects.get(id=id)
        question.delete()
        return Response("deleted") 
        

class InterestListAPIView(ListAPIView):
    serializer_class=InterestListSerializers
    queryset=interest.objects.all()

class ChoiceCreateAPIview(CreateAPIView):
    
    queryset=Choice.objects.all()
    serializer_class=PollCreateSerializers
    permission_classes=[IsAuthenticated,IsAdminUser]

    def perform_create(self,serializer):
        serializer.save(user=self.request.user)
   

polls/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponseRedirect, HttpResponse,JsonResponse
from django.urls import reverse
from .models import Question,Choice,VoteViewCounter
from profileinfo.models import info
from django.contrib.auth.decorators import login_required
from . import forms
from django.core.paginator import Paginator

def index(request):
  
    latest_question_list = Question.objects.order_by('-pub_date')
    message = request.session.get('message')
    paginator=Paginator(latest_question_list,3)
    page=request.GET.get('page')
    if request.GET.get('page'):
        latest_question_list=paginator.page(page)
    else:
        latest_question_list=paginator.page(1)  
    context = {'latest_question_list': latest_question_list}
    if message!="no message":
        context = {'latest_question_list': latest_question_list,'message':message}
        request.session['message'] = "no message"
    return render(request, 'polls/index.html', context)


def profile(request):
    
    latest_question_list = Question.objects.order_by('-pub_date').filter(user=request.user)
    paginator=Paginator(latest_question_list,10)
    page=request.GET.get('page')
    if request.GET.get('page'):
        latest_question_list=paginator.page(page)
    else:
        latest_question_list=paginator.page(1)  
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/profile.html', context)


def test(request):
    
    return render(request, 'polls/polls.html')


def admin(request):
    
    latest_question_list = Question.objects.order_by('-pub_date')
    paginator=Paginator(latest_question_list,10)
    page=request.GET.get('page')
    if request.GET.get('page'):
        latest_question_list=paginator.page(page)
    else:
        latest_question_list=paginator.page(1)  
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/admin.html', context)


@login_required(login_url="/accounts/signin/")    
def detail(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    user=question.user
    counter=VoteViewCounter.objects.get(Question=question)
    voters=counter.votedUser.all()
    viewers=counter.viewedUser.all()
    if request.user in voters:
        voterStatus="voter"
    else:
        voterStatus="non voter"
    if request.is_ajax():
        if request.user in viewers:
            #counting the interest clicks for each question
            print("Viewer")
        else:
            profile=info.objects.all().filter(user=request.user)
            profile=profile[0]
            interests=profile.interest.all()
            if request.user!= question.user:
                question.total+=1
                # loop interests queryset to increment view counter
                for interest in interests:
                    selected=interest.title
                    print(selected)
                    if(selected=='music'):
                        question.music+=1
                    if(selected=='painting'):
                        question.painting+=1
                    if(selected=='peotry'):
                        question.poetry+=1
                    # common question save for every category
                question.save()
                counter.viewedUser.add(request.user)
                counter.save()
    
    
    return render(request, 'polls/details.html', {'question': question,'user':user,'voterstatus':voterStatus})

def getdata(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    # print(question.choices.count())
    choices=question.choices.all()
    listchoice=[]
    datas=[]
    # print(choices.count())
    for i in range(choices.count()):
        listchoice.append(choices[i].choice_text)
        datas.append(choices[i].votes)

    data={
        "choice":listchoice,
        "datas":datas
    }
    print(data)
    return JsonResponse(data)


#showing the result for super-user 
def results(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})


def vote(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    question.vote+=1
    question.save()
    print(question.user)
    try:
        selected_choice = question.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        counter=VoteViewCounter.objects.get(Question=question)
        counter.votedUser.add(request.user)
        counter.save()
        latest_question_list = Question.objects.order_by('-pub_date')
        paginator=Paginator(latest_question_list,3)
        latest_question_list=paginator.page(1)
        message='Thank you for your vote. Please check out other questions'
        request.session['message'] = message
        return redirect("polls:index")


@login_required(login_url="/accounts/signin/")
def createpolls(request):
   
    if request.method=="POST":
        form=forms.createpoll(request.POST)
        choices=forms.takechoice(request.POST)
        #print(request.POST)
        try:
            if form.is_valid and choices.is_valid:
                temp=form.save(commit=False)
                temp.user=request.user
                temp.save()          
                qus=Question.objects.get(question_text=temp.question_text)
                counter=VoteViewCounter(Question=qus)
                counter.save()
                counter.votedUser.add(request.user)
                counter.save()
                counter.viewedUser.add(request.user)
                counter.save()
                x=request.POST.getlist('choice_text')
                #creating 3 choices
                for i in range(len(x)):
                    instance=Choice(question=qus,choice_text=x[i])
                    instance.save()
                #choices.save()
                message='Thank you for creating new question.Please check out other questions'
                request.session['message'] = message
                return redirect('polls:index')
        except:
            error="Your question was not valid!!"
            form=forms.createpoll()
            choices=forms.takechoice()
            return render(request,"polls/createpolls.html",{'form':form,'choice':choices,"error":error})
    else:
        form=forms.createpoll()
        choices=forms.takechoice()
    return render(request,"polls/createpolls.html",{'form':form,'choice':choices})

polls/templates/polls/admin.html
{% extends 'base_layout.html' %}
{% block content %}
{% if user.is_superuser %}
{% if latest_question_list %}
    <br>
    <br>
    <h1 style="text-align:center">Admin Panel</h1>
    <br>
    {% if message %}
    <div class="alert alert-success" >
            {{message}}
    </div>
    {% endif %}
  
    <div class="container">
            <table class="table table-hover">
            <thead>
                <tr>
                <th>Title</th>
                <th>Publication Date</th>
                <th>User</th>
                <th>Tag</th>
                <th>Total View</th>
                <th>Total Vote</th>
                <th>Music Viewer</th>
                <th>Technology</th>
                <th>Poetry</th>
                <th>Painting</th>
                
                </tr>
            </thead>
    {% for question in latest_question_list %}
            <tbody>
                <tr>
                <td> <a href="{% url 'polls:detail' question.id %}" style="text-decoration:none">{{question.question_text}}</a></td>
                <td>{{question.pub_date}}</td>
                <td>{{question.user}}</td>
                <td>{{question.tag}}</td>
                <td>{{question.total}}</td>
                <td>{{question.vote}}</td>
                <td>{{question.music}}</td>
                <td>{{question.technology}}</td>
                <td>{{question.poetry}}</td>
                <td>{{question.painting}}</td>
                <td><form action="">{% csrf_token %} <button type="button" onclick="deletethis('{{question.id}}')" class="btn btn-danger">delete</button></form></td>
                </tr>
                
            </tbody>  
            
    {% endfor %}
    </table>
   <button onclick="payload()" class="btn btn-success">token</button>
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if latest_question_list.has_previous %}
            <a class="btn btn-primary" href="?page=1"> First</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
        </span>

        {% if latest_question_list.has_next %}
            <a class="btn btn-primary" href="?page={{ latest_question_list.next_page_number }}">Next</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.paginator.num_pages }}">Last</a>
        {% endif %}
    </span>
</div>
{% else %}
<div class="alert alert-danger" >
    User is not Admin!!
</div>

{% endif %}
<script>

    function deletethis(id)
    {
        var data={};
        data.csrfmiddlewaretoken=$('input[name=csrfmiddlewaretoken]').val();
       // console.log(data.csrfmiddlewaretoken);
        $.ajax({
             type:'GET',
             url:'http://localhost:8000/api/poll/'+id+'/delete/',
             data:data,
             success:function(data){
                console.log(data);
                document.location.reload(true);
             }
            });
    }

 
    
</script>
{% endblock %}

polls/templates/polls/createpolls.html
{% extends 'base_layout.html' %}
{% block content %}
{% if error %}
<div class="alert alert-danger" >
        {{error}}
</div>
{% endif %}
<br>
<h2>Create new article</h2>
<form action="" method="POST" id="question">
{% csrf_token %}
<div class="form-group">
<label for="Question">Question:</label>
<input type="text" class="form-control" id="Question" name="Question"> 
</div>
<div class="tag-selector" id="tags">

</div>
<div class="choices">
<label for="Choice1">Choice 1:</label>
<input type="text" class="form-control" id="Choice1" name="choice1">

<label for="Choice2">Choice 2:</label>
<input type="text" class="form-control" id="Choice2"  name="choice2">

<label for="Choice3">Choice 3:</label>
<input type="text" class="form-control" id="Choice3"  name="choice3">
</div>
<br>
<button onclick="addoption()" type="button" class="add">+</button>

<br>
<br>
<div id="not-filled-error">

</div>
<button id="create" type="submit" class="btn btn-primary">Submit Question</button>

</form>



<script>
$(document).ready(function(){
        
        $.ajax({
                type:'GET',
                url:'http://localhost:8000/api/poll/interest/',
                success:function(data){
                        tagOptionCreator(data.results);
                        
                }
        });
})
var counter=4;
function addoption(){
        if(counter<=10){
        $(".choices").append(`
        <label for="Choice${counter}">Choice ${counter}:</label>
        <input type="text" class="form-control" id="Choice${counter}"  name="choice${counter}">
        </div>

        `);
        counter=counter+1;
        }
       
}
function tagOptionCreator(tags){
        document.getElementById('tags').innerHTML=`
        <select >
        <option value="0">Select Tag:</option>
        ${tags.map((tag)=>{
               return  `<option value="${tag.id}">${tag.title}</option>`
        }).join(" ")
        }
        </select >
        
        `
}



$( "#create" ).click(function(e) {
        e.preventDefault();
        var data={};
        data.question_text=$('input[name=Question]').val();
        data.tag=$("#tags option:selected").val();
        data.csrfmiddlewaretoken=$('input[name=csrfmiddlewaretoken]').val();
        var options =[];
        for(x=1;x<counter;x++){
                options[x-1]=$(`input[name=choice${x}]`).val();
        }
        data.options=options;
        console.log(data)
        if(true){
                $.ajax({
             type:'POST',
             url:'http://localhost:8000/api/poll/create/',
             dataType: "json",
             beforeSend: function (xhr) {
                
                xhr.setRequestHeader('Authorization', 'Bearer '+localStorage.getItem("token"));
                },
             data:data,
             success:function(data){
                shownotification();
                changepage();
             }
            });
        }
        
});



 function shownotification(){
        $('#toast-place').append(`
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="1000">
      <div class="toast-header">
       
        <strong class="mr-auto text-primary">Success</strong>
        <small class="text-muted">just now</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body text-success">
        Your Question has been added.
      </div>
    </div>
        `);
    $('.toast').toast('show');
    $('.toast').on('hidden.bs.toast',e => {
        $(e.currentTarget).remove();
    });
 }


 function changepage() {
                setTimeout(function(){
                        window.location.replace("http://localhost:8000")
                }, 2000);
                } 

function allfilled(){
        var filled = true;
        for(x=1;x<counter;x++)
        {
        if($(`input[name=choice${x}]`).val()==""){
            filled=false;
            break;
        }
        }
        if(!filled) 
        {
         document.getElementById('not-filled-error').innerHTML=`
         <div class="alert alert-danger">
         Please Fill all options
        </div>
        
        `
        }
        if($("#tags option:selected").val()==0){
                document.getElementById('not-filled-error').innerHTML=`
         <div class="alert alert-danger">
         Please select a tag
        </div>
        
        `   
        filled=false;
        }
        return filled;
}


</script>


{% endblock %}

polls/templates/polls/details.html
{% extends 'base_layout.html' %}
{% block content %}
{% load staticfiles%}
<br>
<h1>{{ question.question_text }}</h1>
{% if error_message %}
<div class="alert alert-danger ">
{{ error_message }}
</div>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<br>
{% for choice in question.choices.all %}

<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

{% endfor %}
<br>

{% if question.user != request.user %}
{% if voterstatus == "voter" %}
<input type="submit" value="Already Voted" class="btn btn-secondary" disabled/>
{% else %}
<input type="submit" value="Vote" class="btn btn-primary"/>
{% endif %}
{% endif %}
</form>
{% if request.user.is_superuser or user == request.user or voterstatus == "voter" %}
<br>
<h3>Result</h3>
<br>
<div id="polls"></div>
<div id="questionList"></div>
{% endif %}
<script>
  
$( document ).ready(function() {

   
    url=window.location.href;
    id=url.slice(27,29);
    var choice=[];
    var datas=[2,3,4];
    $.ajax({
            type: "GET",
            url: '/poll/'+id+'/getdata',
            success:function(data){
                
            },
            error:function(error){
               // console.log(error);
            }
        });
        
});

</script>
<script src="{% static "polls/main.js"%}"></script>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base_layout.html' %}
{% block content %}
{% load staticfiles%}
<br/>
<br/>
<h1 class="title">Latest Questions</h1> 
<div id="questionList"></div>


<!-- <div class="pagination">
    <span class="step-links" id="page-buttons">
       
    </span>
</div>

<script>
    
$(document).ready(function(){
    var link='http://localhost:8000/api/poll/';
    calldata(link); 
 
});

const globalState = {
    next:"",
    previous:""

}
        
function calldata(link)
{
    $.ajax({
        type:'GET',
        url:link,
        success:function(data){
        current=getCurrentpageNumber(data.next,data.previous)
        total=Math.ceil(data.count/3);
        globalState.next=data.next;
        globalState.previous=data.previous;
        var questions=data.results;
        //shows all the given questions from API
        document.getElementById("question-list").innerHTML= `${questionlist(questions)}`;
        //manages page button 
        //buttonmanager(globalState.next,globalState.previous,current,total);

        }
    });
}

function getCurrentpageNumber(next,previous){
    if(!next && !previous)
    {
        return 1;
    }
    else if(next != null)
    {
        nextpage=next.slice(37);
        return parseInt(nextpage)-1
    }
    else if(previous != null)
    {
        if(previous.includes("page"))
        {
        previouspage=previous.slice(37)
        return parseInt(previouspage)+1
        }
        else{
            return 2;
        }
    }
    
}

function buttonmanager(next,previous,current,total){
    if(next==null && previous==null){
        document.getElementById("page-buttons").innerHTML=`
    <button class="btn btn-secondary" onclick="calldata(globalState.previous)" disabled >previous</button> 
    <span class="current">
        Page ${current} of ${total}
    </span>   
    <button class="btn btn-secondary" onclick="calldata(globalState.next)"disabled>next</button>  
    `
    }
    else if (previous==null){
        document.getElementById("page-buttons").innerHTML=`
    <button class="btn btn-secondary" onclick="calldata(globalState.previous)"disabled >previous</button>  
    <span class="current">
        Page ${current} of ${total}
    </span>   
    <button class="btn btn-primary" onclick="calldata(globalState.next)">next</button> 
    `
    }
    else if(next==null){
        document.getElementById("page-buttons").innerHTML=`
    <button class="btn btn-primary" onclick="calldata(globalState.previous)">previous</button> 
    <span class="current">
        Page ${current} of ${total}
    </span>   
    <button class="btn btn-secondary" onclick="calldata(globalState.next)"disabled>next</button>  
    `
    }
    else
    {
        document.getElementById("page-buttons").innerHTML=`
    <button class="btn btn-primary" onclick="calldata(globalState.previous)">previous</button>  
    <span class="current">
        Page ${current} of ${total}
    </span>  
    <button class="btn btn-primary" onclick="calldata(globalState.next)">next</button>     
    `   
    }
    
}

function questionlist(questions){
    return `${questions.map((question)=>{
            return `<div class="card">
            <a href="http://localhost:8000/poll/${question.id}/" style="text-decoration:none;">
            <div class="card-body"> ${question.question_text} </div>
                <div class="card-footer"><Strong>Auther: </Strong> ${question.user}  <Strong>Tag:</Strong>  ${question.tag} </div>
            </a>
            </div>
            <br/>`
        }).join("")}`
}

  
</script> -->
<script src="{% static "polls/main.js"%}"></script>
{% endblock %}

polls/templates/polls/polls.html
{% extends 'base_layout.html' %}
{% block content %}
<form action="" id="test" method="post">
{% csrf_token %}
<button type="submit" id="getdata">click here</button>
</form>
{% endblock %}

polls/templates/polls/profile.html
{% extends 'base_layout.html' %}
{% block content %}
{% if latest_question_list %}
    
       <br>
    <h1 class="title">{{request.user.username|title}}'s Questions </h1>
    <br>
    {% if message %}
    <div class="alert alert-success" >
            {{message}}
    </div>
    {% endif %}
  
    <div class="container">
            <table class="table table-hover">
            <thead>
                <tr>
                <th>Title</th>
                <th>Publication Date</th>
                <th>Tag</th>
                <th>Total View</th>
                <th>Total Vote</th>
                </tr>
            </thead>
    {% for question in latest_question_list %}
            <tbody>
                <tr>
                <td> <a href="{% url 'polls:detail' question.id %}" style="text-decoration:none">{{question.question_text}}</a></td>
                <td>{{question.pub_date}}</td>
                <td>{{question.tag}}</td>
                <td>{{question.total}}</td>
                <td>{{question.vote}}</td>
                </tr>
            </tbody>    
    {% endfor %}
    </table>
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if latest_question_list.has_previous %}
            <a class="btn btn-primary" href="?page=1"> First</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
        </span>

        {% if latest_question_list.has_next %}
            <a class="btn btn-primary" href="?page={{ latest_question_list.next_page_number }}">Next</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.paginator.num_pages }}">Last</a>
        {% endif %}
    </span>
</div>


{% endblock %}

polls/templates/polls/result.html
{% extends 'base_layout.html' %}
{% block content %}
{% if user.is_superuser %}
<h1>{{ question.question_text }}</h1>
<br>
<br>
<ul>

</ul>
{% else %}
<br>
<br>
<div class="alert alert-danger" >
     You are not authorized to see result
</div>
{% endif %}

{% endblock %}