accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns=[

    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^signin/$',views.signin_view,name="signin"),
    url(r'^logout/$',views.logout_view,name="logout"),
    url(r'^personal/$',views.personal_view,name="personal"),
]

bengaltraining/urls.py
from .tokenSerializer import MyTokenObtainPairView
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    url(r'^frontend/',include('frontend.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^poll/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',include('polls.urls')),
    url(r'^api/poll/',include('polls.api.urls',namespace='api')),
    url(r'^api/user/',include('accounts.api.urls',namespace='api-user')),
    url(r'^api/token/$', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^api/token/verify/$', TokenVerifyView.as_view(), name='token_verify'),
]
urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import url
from . import views
app_name='polls'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^profile$',views.profile,name='profile'),
    url(r'^test$',views.test,name='test'),
    url(r'^admin$',views.admin,name='admin'),
    url(r'^createpolls$',views.createpolls,name='createpoll'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/getdata/$', views.getdata, name='getdata'),
    
]

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="csrf-token" content="{{csrf_token}}">
        <title>Bengal Training</title>
        
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    </head>
    <body>
        <header class="wrapper">
           
            <nav class="navbar navbar-expand-sm bg-primary navbar-dark mr-auto">
                <a class="navbar-brand" href="{% url 'polls:index' %}">Bengal-Training</a>
                        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                      <!-- Links -->
                      <div class="collapse navbar-collapse" id="collapse_target">
                      <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:profile' %}">My Questions</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:createpoll' %}">New Question</a>
                        </li> 
                        {% if request.user.is_superuser %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:admin' %}">Admin panel</a>
                        </li> 
                        {% endif %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'accounts:signin' %}">Login</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                        {% endif %}
                      </ul>
                    </div>
                    </nav>
        </header>
        <div class="wrapper-body">
                <div aria-live="polite" aria-atomic="true" style="position: relative; ">
                        <!-- Position it -->
                        <div style="position: fixed; top :10px; right: 0; width:400px" id="toast-place">
                      
                        </div>
                      </div>
            <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        </div>
    </body>
    
</html>


<script>
//for counting user seen
function count(id) {    
    $.ajax({
            type: "GET",
            url: '/poll/'+id,
            data: {
            }
        })
        .done(function( msg ) {
           
        });
}
</script>
<script>
 
  $(document).ready(function(){
        $("#vote").click(function(){
        $(".alert").show("fade");
        
    });
    $(".close").click(function(){
        window.location.replace("/");  
    });
    refreshtoken();
  }); 

  
  function refreshtoken(){
        data={};
        data.refresh=localStorage.getItem("refresh");
        $.ajax({
                type:'POST',
                url:'http://localhost:8000/api/token/refresh/',
                dataType: "json",
                data:data,
                success:function(data){
                localStorage.setItem("token",data.access);
                verify();
                }
               }); 
}
function verify(){
     data={};
        data.token=localStorage.getItem("token")
       
        $.ajax({
                type:'POST',
                url:'http://localhost:8000/api/token/verify/',
                beforeSend: function (xhr) {
                xhr.setRequestHeader('Authorization', 'Bearer '+localStorage.getItem("token"));
                },
                data:data,
                success:function(data){

                console.log("Verified");
                
                },
                error:function(err){
                window.location.replace("http://localhost:8000/signin/")
                }
               }); 
 } 

 function payload() {
        token=localStorage.getItem("token");    
        var base64Url = token.split('.')[1];
        var base64 = base64Url.replace('-', '+').replace('_', '/');
        console.log(JSON.parse(window.atob(base64)));
        }
</script>